remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: pidark
nav_sort: case_sensitive
title: PiBi-Docs
author: Pi Consulting
email: info@piconsulting.com.ar
# logo: "/assets/images/PiBi-rectangle.png"
description: > # this means to ignore newlines until "baseurl:"
  PIBI es una plataforma que permite a una empresa incrustar y distribuir informes en un portal para que clientes, proveedores o colaboradores comerciales puedan interactuar y consumir los mismos a demanda. ​

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage
