remote_theme: "jekyll/minima"
minima:
  skin: dark
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: false
  collections: false
include:
  - Pagina1.md
  - Pagina2.md