remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: pidark
nav_sort: case_sensitive
title: SimplePBIX-Docs
author: La Data Web
email: ibarrau@ladataweb.com.ar
# logo: "/assets/images/PiBi-rectangle.png"
description: > # this means to ignore newlines until "baseurl:"
  SimplePBIX son un conjunto de archivos de Power Bi Desktop que simplifican diversos casos de uso y pueden ser implementados con unos pocos pasos.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage
