remote_theme: hifun-team/hexo-theme-miracle@v2.0.5
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - Pagina1.md
  - README.md
  - Pagina2.md
  - index.md